language: 
    - javascript
os: 
    - linux
    

services:
    - docker

before_install:
    - docker build -t ademardocker/docker-react -f Dockerfile.dev .

script:
    - docker run ademardocker/docker-react npm run test -- --coverage

