os: 
    - linux
    

services:
    - docker


before_install:
    - docker build -t ademardocker/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true ademardocker/docker-react npm run test 


deploy:
    provider: elasticbeanstalk
    access_key_id: "AKIAWHMBL47UH7DMKFGM"
    secret_access_key: "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"
    region: "us-east-1"
    app: "docker_web_server"
    env:"DockerWebServer-env" 
    bucket_name:"elasticbeanstalk-us-east-1-428157429736"
    bucket_path: "docker_web_server"
    on:
        branch: master
  