os: 
    - linux
    

services:
    - docker


before_install:
    - docker build -t ademardocker/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true ademardocker/docker-react npm run test 

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker_web_server"
    env:"DockerWebServer-env" 
    bucket_name:"elasticbeanstalk-us-east-1-428157429736"
    bucket_path: "docker_web_server"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acess_key:
        secure: "AWS_SECRET_KEY"